language: node_js
node_js:
- '6'
script:
- "./prepare.sh"
deploy:
  provider: releases
  prerelease: true
  api_key:
    secure: P+OklHpoSS5SgDp+JwdhxfuhgG141KwoD8G9HEsFb/XxwmfWyz8NMX2LNA2ydyH5ckM25rhkArPuaonhQVHyFnF5twsUtp0HxBR2LtuA5OZtBjEBSRr42O7Am13lZCagq5Jw4PTpiPqmLhO+KSV6qh2mn25rS5mhUfKlOXosbCmK1awK0y8yXAlzWzSrX02ZjRIYLBhgNredl05Y+ehA+nj7lI/Xu/8Hc3HbekM/0WtzWQOlGy/shtK4JzifrOqnlzZZRDdHm324sSO869IHDAVVhHkupx+VW5u6Zuzs2N0xfmgJ5wqTmrjaVmuVJB1to8Y8vgbvy5FpWpGnl/0otKlSXO/mb+5Jvsf7X0ZntBBUJSpDVaarynqJM58AuGwb+aWML4IerWb4socrWvxLN3Ldmi52XwQXlyVP/Dm0Wg3UY8vP4c0FqLiUATSNmcPaXw8r5V4g7b1b1HV98ytKXDugTX7P8gdovdL1iUw/E6Dgx5VmfX5m7WOKFjvVSJUWl7NlOrV2aFgAPyswj5HmKRqKuG8hpk+Ds8nnRtdxs9WBuCSV0MQEO6VQFnpAO8gUuUF82nD9n3OaRLxO3qP+kDcTyKJ5C3OAIEJ4IpS4IZ423pR4wKk6vldt0mm2acnPJ+vHIZGyRWJICzpJrxwMY8kcMrrJYLHyxVatJcv5lq8=
  file:
    - windows.zip
    - linux.zip
    - mac.zip
  on:
    repo: Emano-Waldeck/native-client
